# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_score', models.IntegerField(default=1000)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-elo_score'],
            },
        ),
        migrations.AddField(
            model_name='fight',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_player_fight', to='game.Player'),
        ),
        migrations.AddField(
            model_name='fight',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_player_fight', to='game.Player'),
        ),
    ]
